[package]
name = "risuto-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = "0.5.16"
base64 = "0.13.0"
diesel = { version = "2.0", features = ["sqlite"] }
serde = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
