[package]
name = "risuto-web"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
getrandom = { version = "0.2", features = ["js"] }
gloo-storage = "0.2.2"
reqwest = { version = "0.11.12", features = ["json"] }
risuto-api = { path = "../risuto-api" }
serde = "1.0"
tracing = "0.1.37"
tracing-wasm = "0.2.1"
uuid = "1.2"
yew = "0.19.3"
web-sys = "0.3.60"
