[package]
name = "risuto-web"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
getrandom = { version = "0.2", features = ["js"] }
risuto-api = { path = "../risuto-api" }
yew = "0.19.3"
