# TODO: add --quiet flag to sass when trunk supports it, to silence bootstrap
# warnings

[watch]
watch = [".", "../risuto-api", "../risuto-client"]

[[proxy]]
backend = "ws://localhost:3000/ws/event-feed"
ws = true

[[proxy]]
backend = "http://localhost:3000/api"

