[package]
name = "risuto-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.58"
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.2", features = ["serde", "v4"] }
