[package]
name = "risuto-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bolero.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
serde.workspace = true
uuid.workspace = true
